<?php

namespace Acme\CallendarBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CallendarController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\CallendarBundle\Controller\CallendarController();
        return $instance;
    }
}
