acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_security:
    resource: "@AcmeSecurityBundle/Resources/config/routing.yml"
    prefix:   /

acme_callendar:
    resource: "@AcmeCallendarBundle/Resources/config/routing.yml"
    prefix:   /

